export const MERCHANT_FREE_MAX_SHOPS = 1;
export const MERCHANT_FREE_MAX_ACTIVE_PRODUCTS = 5;

export const MERCHANT_ERROR = {
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
  ACTIVE_PRODUCT_LIMIT: "ACTIVE_PRODUCT_LIMIT",
  SHOP_LIMIT: "SHOP_LIMIT",
  STOCK_UNAVAILABLE: "STOCK_UNAVAILABLE",
  CATEGORY_INACTIVE: "CATEGORY_INACTIVE"
} as const;
