export const MERCHANT_FREE_MAX_SHOPS = 1;
export const MERCHANT_FREE_MAX_ACTIVE_PRODUCTS = 5;

/** Délai d'acceptation commerçant après paiement (24h). */
export const MERCHANT_ORDER_CONFIRM_TIMEOUT_MS = 24 * 60 * 60 * 1000;
/** Fenêtre litige après livraison (48h). */
export const MERCHANT_ORDER_DISPUTE_WINDOW_MS = 48 * 60 * 60 * 1000;

export const MERCHANT_ERROR = {
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
  ACTIVE_PRODUCT_LIMIT: "ACTIVE_PRODUCT_LIMIT",
  SHOP_LIMIT: "SHOP_LIMIT",
  STOCK_UNAVAILABLE: "STOCK_UNAVAILABLE",
  CATEGORY_INACTIVE: "CATEGORY_INACTIVE",
  INVALID_TRANSITION: "INVALID_TRANSITION"
} as const;
