-- Champs vente animal + marqueur revenu auto-généré
ALTER TABLE "Animal" ADD COLUMN "soldAt" TIMESTAMP(3);
ALTER TABLE "Animal" ADD COLUMN "soldWeightKg" DECIMAL(10, 3);
ALTER TABLE "Animal" ADD COLUMN "soldPrice" DECIMAL(14, 2);
ALTER TABLE "Animal" ADD COLUMN "soldCurrency" TEXT;
ALTER TABLE "Animal" ADD COLUMN "buyerName" TEXT;

ALTER TABLE "FarmRevenue" ADD COLUMN "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;
